### ISSUE TITLE
Identity contract constructor takes claims, but claim signature requires address of the identity

### ISSUE THREAD

**Issue by aborovac** [OriginProtocol/identity-playground#12]
The way I read the code:
- Identity constructor takes claims
- a claim contains signature
- in order for claim to valid the signature in the claim needs to be produced by signing identity address
- but identity address doesn't exist, it's about be created

Am I misunderstanding something?

**Comment by nick** [comment]
It's possible to predict the address of a contract that hasn't been created yet... the code we use to do so is [here](https://github.com/OriginProtocol/identity-playground/blob/master/src/pages/identity/modals/_NewIdentity.js#L24-L27). Also see [here](https://ethereum.stackexchange.com/questions/760/how-is-the-address-of-an-ethereum-contract-computed).

This lets us 'pre-sign' claims and add them at identity creation time with a single blockchain transaction.
